### PR TITLE
Do not pin down requirements in Pipfile

### PR DESCRIPTION
**Pull request by fridex**

### CODE REVIEW

**Comment by fridex** [comment]
Anyone to review this please?

**Comment by durandom** [comment]
@fridex didn't see the PR, so sorry for the late reply.

1. do we have bot access already enabled in this org?
2. we dont even have CI enabled for this repo, so before doing this, we should get CI first, I guess

**Comment by fridex** [comment]
> @fridex didn't see the PR, so sorry for the late reply.
> 
> 1. do we have bot access already enabled in this org?

Yes, sesheta is a member of this org. Hopefully that is sufficient.

> 2. we dont even have CI enabled for this repo, so before doing this, we should get CI first, I guess

Yes, that would be definitely good starting point.

**Comment by goern** [comment]
@durandom ping

**Comment by durandom** [comment]
@fridex you're saying "do not pin down versions in Pipfile", but there are still a lot of specific versions in the Pipfile. Am I missing something?

**Comment by tumido** [comment]
Closing because the repo is being retired :wine_glass:

**Pull request closed without merging**
